---
title: "Grammar lessons from my academic writing"
permalink: /blog/grammar-lessons-from-writing/
date: 2024-12-05
layout: postpage
bibliography: refs.bib
link-citations: true
scholar:
  locale: en
output:
  md_document:
    variant: gfm
    preserve_yaml: true
    dev: "png"
    df_print: default
csl: citations.csl
---

# Some grammar for dummies (like me) 

I have learnt from my experience of reading (too few than I am supposed to) papers, that the secret to good writing is to expand your cache of verbs. Not to mention the correct usage of prepositions. (I can never tell if I should write secret _to_ good writing or secret _for_ good writing.)

## that+verb Vs. verb-ing 

`that+verb` should be used while introducing a new subject or before a new clause that requires qualifying a specific action being referred to a subject. Simply put, use `that+verb` to qualify an action. 

_Ex: She admitted that she made a mistake_

 `verb+ing` should be used when the subject is already understood.

_Ex: He enjoys reading_

## to+verb Vs. for+verb+ing

`to+verb` indicates the purpose or intention of an action. 

_Ex: He shouldn’t have joined the army to impress people._

`for+verb+ing` describes the reason or function of something 

_Ex: HE is known for singing beautifully_

## that Vs. which

`that` should be used for restrictive clauses. A restrictive clause is something that limits the meaning of a noun. 

_Ex: The song that you performed right before intermission is my favorite._

`which` should be used for non-restrictive clauses. A non-restrictive clause simply supplies additional information to the noun.

_Ex: These pairs of pants, which no longer fit me, should be given away._

## should be Vs. has to

`should be` means less strict obligation.

- A recommendation or best practice

- A less strict obligation

-  Something that is advisable but not absolutely required

_Ex: The room should be cleaned weekly_ (it's recommended but not mandatory)

`has to` is more strict and is mandatory

- A strict requirement or necessity

- No choice in the matter

- Mandatory action

_Ex: The form has to be submitted by Friday_ (it's absolutely required, no exceptions)

