---
title: "Nucleic acid amplification"
permalink: "/blog/nucleic-acid-amplification"
categories: "DNA Computing"
layout: single
bibliography: refs.bib
link-citations: true
scholar:
  style: apa
  locale: en
output:
  md_document:
    variant: gfm
    preserve_yaml: TRUE
    pandoc_args: 
      - "--wrap=preserve"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../_posts") })

defaults:
- scope:
    path: ''
    type: posts
  values:
    author_profile: false
    read_time: true
    comments: true
    share: true
    related: true
    breadcrumbs: false
tags: dna-computing
---

# Nucleic acid amplification

Nucleic acid amplification (NAA) plays an important rule in pathological testing, especially in the diagnosis of infectious diseases and genetic disorders. Rapid amplification requires the use of enzymes. And so they do.

@Notomi2000 is the first popular model for performing NAA and introduced a method known as Loop-mediated Isothermal Amplification, that uses an arguably incongruous acronym known as LAMP. It is called so because the amplification starts with a primer pairing to a loop in the stem-loop structure. So, it is mediated by the loop.

The method uses DNA Polymerase. The 'target' strand contains *6 recognition sites*. It contains *4 different primers* — 2 inner primers and 2 outer primers.

The amplification process contains *forward* sites and *backward* sites aka 'sense' and 'antisense' strands. So the DNAP action runs in both directions. An interesting point is that the primers are designed so that the action of inner primers is faster than that of the outer primers. The target contains the forward sites on the $3'$ end and the backward sites in the $5'$ end.

The amplification process consists of the following steps:

1.  **Prepare the stem-loop** — Starts from a single-stranded 'target' strand and through a set of DNAP synthesis through inner and outer primers, a double loop structure is formed in the form of dumbbells at both the helix ends. This quickly transforms into a stem-loop structure following a DNAP action.
2.  **Amplification** —
